### ISSUE TITLE
system cannot find the file specified

### ISSUE THREAD

**Issue by priyankanagaraj1494** [IntelVCL/Open3D-PointNet2-Semantic3D#35]
I downloaded and extrcated the dataset.
I am getting this error when trying to run preprocess.py

C:\Users\PNAGARAJ\Lidar\Open3D-PointNet2-Semantic3D-master
file C:\Users\PNAGARAJ\Lidar\Open3D-PointNet2-Semantic3D-master\dataset\semantic_raw\bildstein_station1_xyz_intensity_rgb.txt
txt: C:\Users\PNAGARAJ\Lidar\Open3D-PointNet2-Semantic3D-master\dataset\semantic_raw\bildstein_station1_xyz_intensity_rgb.txt
pts: C:\Users\PNAGARAJ\Lidar\Open3D-PointNet2-Semantic3D-master\dataset\semantic_raw\bildstein_station1_xyz_intensity_rgb.pts
Traceback (most recent call last):
  File "C:/Users/PNAGARAJ/Lidar/Open3D-PointNet2-Semantic3D-master/preprocess.py", line 69, in <module>
    point_cloud_txt_to_pcd(raw_dir, file_prefix)
  File "C:/Users/PNAGARAJ/Lidar/Open3D-PointNet2-Semantic3D-master/preprocess.py", line 49, in point_cloud_txt_to_pcd
    prepend_line(pts_file, str(wc(txt_file)))
  File "C:/Users/PNAGARAJ/Lidar/Open3D-PointNet2-Semantic3D-master/preprocess.py", line 11, in wc
    ["wc", "-l", file_name], stdout=subprocess.PIPE, stderr=subprocess.STDOUT
  File "C:\Users\PNAGARAJ\AppData\Local\Continuum\anaconda3\envs\open3d\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "C:\Users\PNAGARAJ\AppData\Local\Continuum\anaconda3\envs\open3d\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by yxlao** [comment]
Yeah, the CUDA + TensorFlow part is not tested on Windows, please use Ubuntu instead

**Comment by sarraghd** [comment]
Hi, i'm also working on windows and i faced the same problem did you try to solve it please?

**Comment by atineoSE** [comment]
@yxlao I am trying to run through the steps in the README, in particular step 2 "convert txt to pcd file". It seems like there is a mismatch in the expected format, as reported by @sarraghd.

```
$ python preprocess.py 
[txt->pts]
txt: /myPath/Open3D-PointNet2-Semantic3D/dataset/semantic_raw/bildstein_station1_xyz_intensity_rgb.txt
pts: /myPath/Open3D-PointNet2-Semantic3D/dataset/semantic_raw/bildstein_station1_xyz_intensity_rgb.pts
Traceback (most recent call last):
  File "preprocess.py", line 66, in <module>
    point_cloud_txt_to_pcd(raw_dir, file_prefix)
  File "preprocess.py", line 47, in point_cloud_txt_to_pcd
    prepend_line(pts_file, str(wc(txt_file)))
  File "preprocess.py", line 13, in wc
    return int(out.partition(b" ")[0])
ValueError: invalid literal for int() with base 10: b''
```

**Comment by sarraghd** [comment]
@atineoSE this is because ''wc'' is not known by windows, you should use ubuntu instead.

**Comment by yangfeifan-ufo** [comment]
I met the same problem
