### ISSUE TITLE
ask for kitti demo

### ISSUE THREAD

**Issue by amiltonwong** [IntelVCL/Open3D-PointNet2-Semantic3D#42]
Hi, @yxlao ,

The provided code only guides how to deal with Semantic3D dataset. From your Open3D 0.5 introduction [video](https://youtu.be/QNVJEI_g4rw?t=65), real-time inference in KITTI lidar dataset is presented. Would you also update the pipeline for KITTI lidar dataset?

THX!

**Comment by yxlao** [comment]
@amiltonwong 
For training, use `train.py` and `semantic_no_color.json` config.
For inference, use `kitti_predict.py`.

**Comment by coronax1016** [comment]
hi @yxlao 
I think we also miss the preprocessing part from raw kitti to pcd files

**Comment by iris0329** [comment]
Hi @coronax1016, 
If you just test the pre-trained model provided by the author, you don't have to deal with raw KITTI data, because the python library imported in the 'kitti_predict.py' can handle KITTI data by itself.
I only download the KITTI, and run 'kitti_predict.py', it works !

**Comment by kmns2pr** [comment]
I want to try this demo project. so I run "python3 kitti_predict.py --kitti_root ./dataset/kitti_raw" . but i got error below 

python3 kitti_predict.py --kitti_root ./dataset/kitti_raw/
/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Loading date: 2011_09_26, drive: 0001
2020-02-03 12:10:06.566439: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "kitti_predict.py", line 148, in <module>
    hyper_params=hyper_params,
  File "kitti_predict.py", line 81, in __init__
    saver.restore(self.sess, checkpoint_path)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1538, in restore
    + compat.as_text(save_path))
ValueError: The passed save_path is not a valid checkpoint: 

what should i do to reslove this error?

**Comment by davidlmljll** [comment]
Hello @iris0329, can you tell me how you run the 'kitti_predict.py'  and thedata needs to be preprocessed?
