### ISSUE TITLE
'tensorflow' has no attribute '__cxx11_abi_flag__'

### ISSUE THREAD

**Issue by yulongyu** [IntelVCL/Open3D-PointNet2-Semantic3D#45]
when i compile tf_ops,An error occurred 'tensorflow' has no attribute '__cxx11_abi_flag__'
in "FindTensorFlow.cmake" has a code ：
python -c "import tensorflow as tf;
I think I has install tensorflow 1.2 right,How can I solve this problem?
thanks

**Comment by yulongyu** [comment]
> when i compile tf_ops,An error occurred 'tensorflow' has no attribute '**cxx11_abi_flag**'
> in "FindTensorFlow.cmake" has a code ：
>python -c "import tensorflow as tf; print(tf.__cxx11_abi_flag__)"
> I think I has install tensorflow 1.2 right,How can I solve this problem?
> thanks

**Comment by yulongyu** [comment]
is version tensorflow 1.2???

**Comment by yxlao** [comment]
Just verified under TF `1.12.0`, maybe try upgrading. TF `1.2` is pretty old.

**Comment by tianchengdw** [comment]
> Just verified under TF `1.12.0`, maybe try upgrading. TF `1.2` is pretty old.
Hi, Thanks for the great work! I use TF1.12 ,cuda9.0 and cudnn7.4.2. And I also got  libtf_grouping.so libtf_interpolate.so libtf_sampling.so. But I met the error when I run test_tf_ops.py. 
`Traceback (most recent call last):
  File "test_tf_ops.py", line 4, in <module>
    from tf_grouping import query_ball_point, group_point, knn_point
  File "/media/orange/work/Open3D-PointNet2-Semantic3D-master/tf_ops/tf_grouping.py", line 9, in <module>
    os.path.join(BASE_DIR, "build", "libtf_grouping.so")
  File "/home/orange/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /media/orange/work/Open3D-PointNet2-Semantic3D-master/tf_ops/build/libtf_grouping.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv`

**Comment by coronax1016** [comment]
Hi, Same problems when using tf 1.13.1 compile the tf_ops with cuda 10 and cudnn 7.5
-- Looking for TensorFlow installation
-- TensorFlow_INCLUDE_DIR: /usr/local/lib/python2.7/dist-packages/tensorflow/include
-- TensorFlow_DIR: /usr/local/lib/python2.7/dist-packages/tensorflow/core
CMake Error at FindTensorFlow.cmake:72 (message):
  Cannot determine TensorFlow __cxx11_abi_flag__

  Traceback (most recent call last):

    File "<string>", line 1, in <module>

  AttributeError: 'module' object has no attribute '__cxx11_abi_flag__'
Call Stack (most recent call first):
  CMakeLists.txt:25 (find_package)

Thanks

**Comment by yulongyu** [comment]
> > Just verified under TF `1.12.0`, maybe try upgrading. TF `1.2` is pretty old.
> 
> @yxlao Hi, Thanks for the great work! I use TF1.12 ,cuda9.0 and cudnn7.4.2. And I also got libtf_grouping.so libtf_interpolate.so libtf_sampling.so. But I met the error when I run test_tf_ops.py.
> `Traceback (most recent call last): File "test_tf_ops.py", line 4, in <module> from tf_grouping import query_ball_point, group_point, knn_point File "/media/orange/work/Open3D-PointNet2-Semantic3D-master/tf_ops/tf_grouping.py", line 9, in <module> os.path.join(BASE_DIR, "build", "libtf_grouping.so") File "/home/orange/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library lib_handle = py_tf.TF_LoadLibrary(library_filename) tensorflow.python.framework.errors_impl.NotFoundError: /media/orange/work/Open3D-PointNet2-Semantic3D-master/tf_ops/build/libtf_grouping.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv`

i got the same question when i use other computer, how you sove it?????????
